import 'package:connect/data/providers/hive_service.dart';
import 'package:hive/hive.dart';

part 'message_hive_data.g.dart'; // This file will be generated by Hive using `build_runner`

@HiveType(typeId: 1)
class MessageHiveData {
  @HiveField(0)
  final String senderId;

  @HiveField(1)
  String message;

  @HiveField(2)
  final String name;

  @HiveField(3)
  final String? avater;

  @HiveField(4)
  bool isSeen;

  @HiveField(5)
  final bool isTyping;

  @HiveField(6)
  DateTime timestamp;

  @HiveField(7) // Add this line for recipientId
  final String recipientId; // New field for recipientId
  @HiveField(8) // Add this for _id
  final String messageId; // New field for storing the message ID (_id)
  @HiveField(9) // Add this for _id
  final String repliedMsgId;
  MessageHiveData({
    required this.senderId,
    required this.message,
    required this.name,
    this.avater,
    this.isSeen = false,
    required this.isTyping,
    required this.repliedMsgId,
    required this.messageId, // Add required _id field
    required this.timestamp,
    String? recipientId, // Change this line
  }) : recipientId = recipientId ??
            HiveService.instance.userData?.id ??
            ''; // Default value
}

//flutter packages pub run build_runner build