name: connect
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  velocity_x: ^4.2.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  intl_phone_field: ^3.2.0
  dio: ^5.7.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.4
  intl: ^0.19.0
  socket_io_client: ^3.0.0
  just_audio: ^0.9.41
  flutter_local_notifications: ^17.2.3
  flutter_cache_manager: ^3.4.1
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  